CREATE TABLE IF NOT EXISTS moviles(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    SO VARCHAR(7) NOT NULL,
    Almacenamiento INTEGER NOT NULL,
    Ram INTEGER NOT NULL,
    Url VARCHAR(300) NOT NULL,
    Precio FLOAT(5, 2) NOT NULL,
    Imagen LONGBLOB NOT NULL
);