CREATE TABLE IF NOT EXISTS moviles(
    EAN VARCHAR(13),
    Nombre VARCHAR(100),
    Marca VARCHAR(18) NOT NULL,
    Descripcion VARCHAR(500),
    Modelo VARCHAR(25) NOT NULL,
    PRIMARY KEY (EAN)
);

CREATE TABLE IF NOT EXISTS caracteristicas(
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    EAN VARCHAR(13) NOT NULL,
    Clave VARCHAR(50),
    Valor VARCHAR(150),
    PRIMARY KEY (id),
    FOREIGN KEY (EAN) REFERENCES moviles(EAN)
);

CREATE TABLE IF NOT EXISTS precios(
    EAN VARCHAR(13) NOT NULL,
    Precio DECIMAL(6, 2) NOT NULL,
    Url VARCHAR(200) NOT NULL,
    Imagen VARCHAR(170),
    PRIMARY KEY (Url),
    FOREIGN KEY (EAN) REFERENCES moviles(EAN)
);